{{- if or .Values.keycloak.user.password .Values.keycloak.realm.client_secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic-chart.fullname" . }}-secret
data:
  {{- if .Values.keycloak.user.password }}
  keycloak_user_name: {{ default "" .Values.keycloak.user.name | b64enc | quote }}
  keycloak_user_password: {{ default "" .Values.keycloak.user.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.keycloak.realm.client_secret }}
  keycloak_client_secret: {{ toString .Values.keycloak.realm.client_secret | b64enc | quote }}
  {{- end }}
{{- end }}