# Default values for metadatasearch-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ""
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

container:
  main:
    ports:
      - name: http
        port: 8080
        protocol: TCP
    env:
      COMPLIANCE_SERVICE_URL: ""
      FEDERATED_CATALOGUE_URL: ""
      SD_CREATOR_URL: ""
    probes:
      readiness:
        path: /q/health/ready
        port: 8080
      liveness:
        path: /q/health/live
        port: 8080
      startup:
        path: /q/health/start
        port: 8080

# Note: Each service ports definition must link to a container.main.ports definition
service:
  type: ClusterIP
  ingressPort: 8080 # Points to one of the service ports below
  ports:
    - name: http
      port: 8080
      targetPort: 8080 # Link to a related definition of container.main.ports.name or container.main.ports.port
      protocol: TCP

secrets:
  KEYCLOAK_USER_PASSWORD:
    secretName: claim-compliance-provider-secret
    secretKey: keycloak_user_password
  KEYCLOAK_CLIENT_SECRET:
    secretName: claim-compliance-provider-secret
    secretKey: keycloak_client_secret
  KEYCLOAK_USER_NAME:
    secretName: claim-compliance-provider-secret
    secretKey: keycloak_user_name

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

# podSecurityContext:
#   fsGroup: 1000
#   fsGroupChangePolicy: "OnRootMismatch"

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ingress:
  enabled: true
  className: nginx
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
   requests:
     cpu: 50m
     memory: 100M

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations:
  - key: "kubernetes.azure.com/scalesetpriority"
    operator: "Equal"
    value: "spot"
    effect: "NoSchedule"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: "kubernetes.azure.com/scalesetpriority"
              operator: In
              values:
                - "spot"

keycloak:
  realm:
    client_secret: "" # Client secret to access Keycloak
  user:
    name: ""
    password: ""